// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYMMO-VW6NkVnZZ9YFCEVKJNDyX4ZxxR0',
    appId: '1:971176164313:web:0fceddf6388d64aba437c8',
    messagingSenderId: '971176164313',
    projectId: 'subz-685eb',
    authDomain: 'subz-685eb.firebaseapp.com',
    storageBucket: 'subz-685eb.appspot.com',
    measurementId: 'G-M51WJQ7K72',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXr-hB6uxxMfs1csfHJdxMiF7EBAufTCI',
    appId: '1:971176164313:android:10c74c5e203cc677a437c8',
    messagingSenderId: '971176164313',
    projectId: 'subz-685eb',
    storageBucket: 'subz-685eb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7F45kTgK7Q2_XvXQoScUUZY_qK3s0gOs',
    appId: '1:971176164313:ios:5dfb1e40fa57f5a3a437c8',
    messagingSenderId: '971176164313',
    projectId: 'subz-685eb',
    storageBucket: 'subz-685eb.appspot.com',
    iosClientId: '971176164313-o9tdii711eseb7fuc3u01j3ah0qgjvum.apps.googleusercontent.com',
    iosBundleId: 'com.example.subz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7F45kTgK7Q2_XvXQoScUUZY_qK3s0gOs',
    appId: '1:971176164313:ios:5dfb1e40fa57f5a3a437c8',
    messagingSenderId: '971176164313',
    projectId: 'subz-685eb',
    storageBucket: 'subz-685eb.appspot.com',
    iosClientId: '971176164313-o9tdii711eseb7fuc3u01j3ah0qgjvum.apps.googleusercontent.com',
    iosBundleId: 'com.example.subz',
  );
}
